"""
Feature engineering and data loaders for the Tiny Recursive Model (TRM).

This module orchestrates S3 downloads, feature creation and conversion to
PyTorch DataLoaders tailored for the TRM architecture.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, TensorDataset

from data.s3_data_source import S3DataSource

logger = logging.getLogger(__name__)


def build_trm_features(
    df: pd.DataFrame,
    *,
    lookback_window: int = 60,
    prediction_horizon: int = 1,
    normalize: bool = True,
    drop_na: bool = True,
) -> pd.DataFrame:
    """
    Enrich OHLCV data with TRM-friendly features.

    Args:
        df: DataFrame containing columns timestamp, open, high, low, close, volume, symbol.
        lookback_window: Rolling window used for statistics.
        prediction_horizon: Steps ahead to predict (in minutes for 1m data).
        normalize: Apply z-score normalization per feature.
        drop_na: Drop rows with NaNs generated by rolling computations.

    Returns:
        DataFrame with timestamp, engineered features and a `target` column (future return).
    """
    if df.empty:
        raise ValueError("Input dataframe is empty, cannot build TRM features.")

    data = df.sort_values("timestamp").reset_index(drop=True).copy()
    window = max(5, lookback_window)

    # Basic returns
    data["return_1"] = data["close"].pct_change()
    data["return_5"] = data["close"].pct_change(periods=5)
    data["return_15"] = data["close"].pct_change(periods=15)

    # Log volume captures magnitude while damping outliers
    data["log_volume"] = np.log(data["volume"].astype(float) + 1.0)

    # Volatility estimate
    data["rolling_volatility"] = data["return_1"].rolling(window).std()

    # Price position relative to rolling min/max
    rolling_max = data["high"].rolling(window).max()
    rolling_min = data["low"].rolling(window).min()
    range_span = (rolling_max - rolling_min).replace(0, np.nan)
    data["price_position"] = (data["close"] - rolling_min) / range_span

    # Ratio to moving average encodes regime/momentum
    rolling_mean = data["close"].rolling(window).mean()
    data["ma_ratio"] = data["close"] / rolling_mean - 1.0

    # Volume surprise (z-score)
    volume_mean = data["volume"].rolling(window).mean()
    volume_std = data["volume"].rolling(window).std().replace(0, np.nan)
    data["volume_zscore"] = (data["volume"] - volume_mean) / volume_std

    # Target: future return after `prediction_horizon`
    data["target"] = data["close"].pct_change(periods=prediction_horizon).shift(-prediction_horizon)

    feature_cols = [
        "return_1",
        "return_5",
        "return_15",
        "rolling_volatility",
        "price_position",
        "ma_ratio",
        "volume_zscore",
        "log_volume",
    ]

    if drop_na:
        data = data.dropna(subset=feature_cols + ["target"])
    else:
        data = data.fillna(method="ffill").fillna(method="bfill")

    if data.empty:
        raise ValueError("Feature engineering removed all rows; not enough history.")

    if normalize:
        # Normalize features ONLY (not target - done globally after)
        for col in feature_cols:
            col_std = data[col].std()
            if col_std is None or col_std == 0:
                continue
            data[col] = (data[col] - data[col].mean()) / col_std

    columns = ["timestamp"] + feature_cols + ["target"]
    return data[columns]


def create_dataloaders(
    sequences: np.ndarray,
    targets: np.ndarray,
    batch_size: int,
    train_ratio: float,
    val_ratio: float,
    test_ratio: float,
    *,
    num_workers: int = 0,
    pin_memory: bool = False,
) -> Tuple[DataLoader, DataLoader, DataLoader, dict]:
    """
    Split arrays into chronological train/val/test DataLoaders with PROPER STANDARDIZATION.

    CRITICAL: Only train set is used to compute mean/std for normalization.
    Returns normalization stats for inverse transform during evaluation.
    """
    total = len(sequences)
    if total == 0:
        raise ValueError("No sequences available to create dataloaders.")

    # Ensure ratios fall between 0 and 1
    train_ratio = min(max(train_ratio, 0.0), 0.9)
    val_ratio = min(max(val_ratio, 0.0), 0.49)
    test_ratio = min(max(test_ratio, 0.0), 1.0)

    train_end = max(1, int(total * train_ratio))
    val_end = max(train_end + 1, int(total * (train_ratio + val_ratio)))
    val_end = min(val_end, total - 1)

    if val_end <= train_end:
        val_end = min(train_end + max(1, total // 10), total - 1)

    # Remaining samples go to test split
    train_slice = slice(0, train_end)
    val_slice = slice(train_end, val_end)
    test_slice = slice(val_end, total)

    # CRITICAL: Normalize targets using TRAIN set statistics only
    train_targets = targets[train_slice]
    target_mean = np.mean(train_targets)
    target_std = np.std(train_targets)

    if target_std == 0 or np.isnan(target_std):
        logger.warning("Target std is 0 or NaN, setting to 1.0")
        target_std = 1.0

    logger.info(f"Normalizing targets: train_mean={target_mean:.6f}, train_std={target_std:.6f}")

    # Apply normalization to ALL targets using train statistics
    targets_normalized = (targets - target_mean) / target_std

    # Verify normalization
    train_norm_mean = np.mean(targets_normalized[train_slice])
    train_norm_std = np.std(targets_normalized[train_slice])
    logger.info(f"Normalized train targets: mean={train_norm_mean:.6f}, std={train_norm_std:.6f}")

    # DEBUG: Print first 5 normalized targets
    logger.info(f"First 5 normalized train targets: {targets_normalized[:5]}")

    def _to_loader(data_slice: slice) -> DataLoader:
        tensor_x = torch.from_numpy(sequences[data_slice]).float()
        tensor_y = torch.from_numpy(targets_normalized[data_slice]).float().unsqueeze(-1)

        # DEBUG: Verify tensor is normalized
        logger.info(f"Tensor y for {data_slice}: mean={tensor_y.mean().item():.6f}, std={tensor_y.std().item():.6f}")

        dataset = TensorDataset(tensor_x, tensor_y)
        return DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=False,
            drop_last=False,
            num_workers=num_workers,
            pin_memory=pin_memory,
        )

    # Return normalization stats for inverse transform
    norm_stats = {
        'target_mean': float(target_mean),
        'target_std': float(target_std)
    }

    return _to_loader(train_slice), _to_loader(val_slice), _to_loader(test_slice), norm_stats


@dataclass
class S3TRMDataLoader:
    """
    Load historical crypto data from S3 and prepare TRM-ready DataLoaders.
    """

    s3_bucket: str
    s3_prefix: str
    start_year: int
    end_year: int
    symbols: Optional[Sequence[str]] = None
    lookback_window: int = 60
    batch_size: int = 128
    cache_dir: Optional[str] = None
    train_ratio: float = 0.7
    val_ratio: float = 0.15
    test_ratio: float = 0.15
    num_workers: int = 0
    pin_memory: bool = False
    cache_local_data: bool = True

    def __post_init__(self):
        self.data_source = S3DataSource(
            bucket=self.s3_bucket,
            prefix=self.s3_prefix,
            cache_dir=self.cache_dir,
        )

    def _resolve_symbols(self, symbol_override: Optional[str]) -> List[str]:
        if symbol_override:
            return [symbol_override]
        if self.symbols:
            return list(self.symbols)

        available = self.data_source.list_available_symbols(self.start_year)
        if not available:
            raise RuntimeError(
                "Unable to infer available symbols from S3. Provide `symbols` in the config."
            )
        return available

    def _download_dataframe(self, symbols: List[str]) -> pd.DataFrame:
        df = self.data_source.fetch_all_symbols_range(symbols, self.start_year, self.end_year)
        if df.empty:
            raise RuntimeError(
                f"No data downloaded for symbols {symbols} between {self.start_year}-{self.end_year}"
            )
        return df

    def _build_sequences(
        self,
        df: pd.DataFrame,
        *,
        prediction_horizon: int,
        normalize: bool,
    ) -> Tuple[np.ndarray, np.ndarray, int]:
        sequences = []
        targets = []
        feature_dim = None

        for symbol, group in df.groupby("symbol"):
            try:
                features_df = build_trm_features(
                    group,
                    lookback_window=self.lookback_window,
                    prediction_horizon=prediction_horizon,
                    normalize=normalize,
                    drop_na=True,
                )
            except ValueError as exc:
                logger.warning("Skipping %s: %s", symbol, exc)
                continue

            feature_cols = [col for col in features_df.columns if col not in ("timestamp", "target")]
            feature_matrix = features_df[feature_cols].to_numpy(dtype=np.float32)
            targets_vector = features_df["target"].to_numpy(dtype=np.float32)

            if feature_dim is None:
                feature_dim = feature_matrix.shape[1]

            if len(feature_matrix) <= self.lookback_window:
                logger.warning("Not enough timesteps for %s after feature engineering.", symbol)
                continue

            for idx in range(self.lookback_window, len(feature_matrix)):
                seq = feature_matrix[idx - self.lookback_window : idx]
                target = targets_vector[idx]
                sequences.append(seq)
                targets.append(target)

        if not sequences:
            raise RuntimeError("No sequences constructed for TRM training.")

        sequences_np = np.stack(sequences, axis=0)
        targets_np = np.asarray(targets, dtype=np.float32)

        return sequences_np, targets_np, feature_dim or sequences_np.shape[-1]

    def prepare_dataloaders(
        self,
        symbol: Optional[str] = None,
        normalize: bool = True,
        prediction_horizon: int = 1,
    ):
        """
        Download data, create sequences and return DataLoaders plus metadata.
        """
        symbols = self._resolve_symbols(symbol)
        df = self._download_dataframe(symbols)
        sequences, targets, num_features = self._build_sequences(
            df,
            prediction_horizon=prediction_horizon,
            normalize=normalize,
        )

        train_loader, val_loader, test_loader, norm_stats = create_dataloaders(
            sequences,
            targets,
            self.batch_size,
            self.train_ratio,
            self.val_ratio,
            self.test_ratio,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
        )

        metadata = {
            "train_samples": len(train_loader.dataset),
            "val_samples": len(val_loader.dataset),
            "test_samples": len(test_loader.dataset),
            "num_features": num_features,
            "lookback_window": self.lookback_window,
            "symbols": symbols,
            # CRITICAL: Include normalization stats for inverse transform
            "target_mean": norm_stats['target_mean'],
            "target_std": norm_stats['target_std'],
        }

        return train_loader, val_loader, test_loader, metadata


__all__ = [
    "S3TRMDataLoader",
    "build_trm_features",
    "create_dataloaders",
]
