#!/bin/bash
# 🐋 FREE WHALE SCANNER - Commandes Rapides

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              🐋 FREE WHALE SCANNER - COMMANDES                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 COMMANDES DISPONIBLES:"
echo ""
echo "1. Test rapide (10 blocs Bitcoin):"
echo "   python run_whale_scanner.py --test"
echo ""
echo "2. Scan Bitcoin (100 blocs):"
echo "   python run_whale_scanner.py --blockchain btc --limit 100"
echo ""
echo "3. Scan Ethereum (50 blocs - clé API requise):"
echo "   python run_whale_scanner.py --blockchain eth --limit 50 --api-key YOUR_KEY"
echo ""
echo "4. Visualiser les données:"
echo "   python view_blockchain_whales.py"
echo ""
echo "5. Help complet:"
echo "   python run_whale_scanner.py --help"
echo ""
echo "📚 Documentation: FREE_WHALE_README.md"
echo ""
