app: trading-system-dev
include: base.yaml

data_layer:
  mongo_buffer:
    uri: mongodb://localhost:27017
    db: market_dev
    collection: buffer_events
  s3_lake:
    bucket: dev-bucket
    prefix: s3://dev-bucket
