app: trading-system-prod
include: base.yaml

data_layer:
  mongo_buffer:
    uri: mongodb://prod-mongo:27017
    db: market_prod
    collection: buffer_events
  s3_lake:
    bucket: prod-bucket
    prefix: s3://prod-bucket
