{
  "type": "record",
  "name": "ExecutedFills",
  "namespace": "trading.system",
  "fields": [
    {"name": "event_time", "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "symbol", "type": "string"},
    {"name": "side", "type": "string"},
    {"name": "qty", "type": "double"},
    {"name": "price", "type": "double"},
    {"name": "fee_usd", "type": "double"},
    {"name": "liquidity", "type": "string"},
    {"name": "exchange", "type": "string"},
    {"name": "client_order_id", "type": "string"},
    {"name": "order_id", "type": "string"},
    {"name": "run_id", "type": "string"}
  ]
}
