from __future__ import annotations

from typing import Dict

from ..contracts import DataDomain, ExecutionStyle
from .base import LabSpec


def _spec(lab_id, name, source, hypothesis, payer, domains, plugin, target, horizons, styles, max_trials, patterns, any_groups=()):
    return LabSpec(lab_id=lab_id, name=name, economic_source_id=source, hypothesis_template=hypothesis, payer=payer, domains=tuple(domains), plugin=plugin, default_target=target, horizons_ms=tuple(int(x) for x in horizons), execution_styles=tuple(styles), max_trials_per_family=int(max_trials), required_column_patterns=tuple(patterns), required_any_groups=tuple(tuple(g) for g in any_groups))


LABS: Dict[str, LabSpec] = {
    "A1": _spec("A1", "Cross-venue price discovery", "cross_venue_price_discovery", "Venue innovations lead peer repricing.", "slower venue inventory", [DataDomain.BOOK, DataDomain.TRADE], "cross_venue", "loo_fair_value_return", [25,50,100,250,500,1000,2000,5000], [ExecutionStyle.HYBRID], 40, ["*__price_mid", "*__price_dislocation_bps"]),
    "A2": _spec("A2", "Venue dislocation convergence", "venue_dislocation_convergence", "Transient venue dislocations converge to a robust anchor.", "urgent local flow", [DataDomain.BOOK], "cross_venue", "loo_fair_value_return", [100,250,500,1000,2000,5000,10000,30000], [ExecutionStyle.HEDGE], 32, ["*__price_dislocation_bps"]),
    "A3": _spec("A3", "Queue depletion hazard", "queue_depletion_hazard", "Conditional add/cancel/execution intensity predicts first queue depletion.", "adverse selected passive liquidity", [DataDomain.BOOK, DataDomain.TRADE], "event_microstructure", "next_mid_move", [25,50,100,250,500,1000,2000], [ExecutionStyle.MAKER], 48, [], [("*ofi*", "*queue_imbalance*"), ("*cancel*", "*remove*")]),
    "A4": _spec("A4", "Liquidity resilience", "liquidity_resilience", "Refill asymmetry after a sweep separates continuation from rejection.", "shock extrapolators", [DataDomain.BOOK, DataDomain.TRADE], "event_microstructure", "fair_value_return", [100,250,500,1000,2000,5000,10000,30000], [ExecutionStyle.FILTER], 40, [], [("*trades_per_second*", "*signed_notional*"), ("*depth_*", "*notional_to_move*")]),
    "A5": _spec("A5", "Toxic flow and absorption", "toxic_trade_flow", "Signed flow versus impact identifies informed toxicity or hidden absorption.", "late market-order followers", [DataDomain.TRADE, DataDomain.BOOK], "event_microstructure", "fair_value_return", [100,250,500,1000,2000,5000,10000,30000], [ExecutionStyle.HYBRID], 48, [], [("*signed_notional*", "*flow_imbalance*"), ("*absorption*", "*impact_bps*")]),
    "A6": _spec("A6", "Liquidity shock propagation", "liquidity_shock_propagation", "Depth/spread shocks on leaders propagate with measurable impulse response.", "slow cross-venue repricing", [DataDomain.BOOK], "shock_propagation", "loo_fair_value_return", [100,250,500,1000,2000,5000,10000,30000], [ExecutionStyle.TAKER], 32, [], [("*spread_bps*",), ("*depth_*", "*notional_to_move*")]),
    "A7": _spec("A7", "Liquidation cascade", "liquidation_cascade", "Forced liquidations become nonlinear relative to available depth and OI.", "leveraged forced flow", [DataDomain.DERIVATIVES, DataDomain.BOOK], "leverage", "fair_value_return", [1000,2000,5000,10000,30000,60000,300000], [ExecutionStyle.TAKER], 36, [], [("*liquidation*",), ("*open_interest*",)]),
    "A8": _spec("A8", "Leverage topology", "leverage_positioning", "Joint price/OI/funding/basis state distinguishes new leverage from deleveraging.", "crowded leverage", [DataDomain.DERIVATIVES, DataDomain.SPOT], "leverage", "fair_value_return", [10000,30000,60000,300000,900000,3600000], [ExecutionStyle.FILTER], 48, [], [("*open_interest*",), ("*funding*", "*basis*", "*premium*")]),
    "A9": _spec("A9", "Funding basis convergence", "funding_basis_convergence", "Extreme carry/basis deviations converge under arbitrage capital.", "perp carry payers", [DataDomain.DERIVATIVES, DataDomain.SPOT], "funding_basis", "basis_convergence", [60000,300000,900000,3600000,14400000], [ExecutionStyle.HEDGE], 28, [], [("*funding*",), ("*basis*", "*premium*")]),
    "A10": _spec("A10", "Funding settlement event", "funding_settlement_event", "Funding boundaries create predictable inventory adjustment around settlement.", "funding-sensitive inventory", [DataDomain.DERIVATIVES, DataDomain.EVENT], "funding_basis", "fair_value_return", [60000,300000,900000,1800000,3600000], [ExecutionStyle.FILTER], 24, [], [("*funding*",), ("*time_to_funding*", "*funding_clock*")]),
    "A11": _spec("A11", "Informed wallet flow", "wallet_informed_flow", "Persistent public-wallet markout identifies informed flow before broad repricing.", "less-informed counterparties", [DataDomain.WALLET, DataDomain.TRADE], "wallet", "fair_value_return", [1000,5000,10000,30000,60000,300000], [ExecutionStyle.FILTER], 32, ["wallet__*"]),
    "A12": _spec("A12", "Cross-asset causal propagation", "cross_asset_propagation", "Leader innovations predict follower residual returns.", "slow cross-asset repricing", [DataDomain.CROSS_ASSET], "cross_asset", "fair_value_return", [100,250,500,1000,2000,5000,10000,30000,60000,300000], [ExecutionStyle.HEDGE], 48, [], [("cross_asset__*", "*innovation*"), ("*residual*",)]),
    "A13": _spec("A13", "Residual relative value", "residual_relative_value", "Factor-neutral residual divergence mean-reverts independent of market beta.", "temporary inventory imbalance", [DataDomain.CROSS_ASSET, DataDomain.SPOT], "cross_asset", "fair_value_return", [60000,300000,900000,3600000,14400000], [ExecutionStyle.HEDGE], 32, [], [("*residual*",), ("*beta*",)]),
    "A14": _spec("A14", "Options surface shock", "options_surface_shock", "IV/skew/term shocks predict hedging pressure and realized-vol repricing.", "convexity rehedging", [DataDomain.OPTIONS, DataDomain.DERIVATIVES], "options", "future_realized_vol", [60000,300000,900000,3600000], [ExecutionStyle.HEDGE], 32, [], [("*iv_*", "*skew*", "*rr25*"), ("*option_oi*", "*gamma*")]),
    "A15": _spec("A15", "On-chain exchange flow", "onchain_exchange_flow", "Exchange/stablecoin inventory changes shift future supply-demand.", "slower settlement-layer responders", [DataDomain.ONCHAIN, DataDomain.SPOT], "onchain", "fair_value_return", [300000,900000,3600000,14400000,86400000], [ExecutionStyle.FILTER], 24, [], [("onchain__*", "*exchange_netflow*", "*stablecoin*")]),
    "A16": _spec("A16", "Execution alpha", "execution_alpha", "Queue state and flow predict fill probability and post-fill adverse selection.", "immediacy demanders", [DataDomain.EXECUTION, DataDomain.BOOK, DataDomain.TRADE], "execution", "post_fill_markout", [25,50,100,250,500,1000,5000,30000], [ExecutionStyle.MAKER], 48, [], [("*queue_ahead*", "*fill_probability*"), ("*markout*", "*latency*")]),
}
