#!/usr/bin/env python3
"""
Trading System Main Entry Point

Modes:
  - live: Run live trading
  - backtest: Run historical backtest
  - train: Train ML models
  - validate: Validate configuration and data
"""

from __future__ import annotations

import argparse
import logging
import sys
import uuid
from pathlib import Path

import numpy as np

from common.logging.setup import get_logger
from infra.config.loader import load_config

logger = get_logger(__name__)


def run_live(config_path: str, symbols: list[str]) -> int:
    """Run live trading mode."""
    logger.info({"msg": "Starting live trading", "config": config_path, "symbols": symbols})

    try:
        config = load_config(config_path)
        logger.info({"msg": "Config loaded", "app": config.get("app", "unknown")})

        # TODO: Implement live pipeline
        logger.warning({"msg": "Live trading not yet implemented"})
        return 1

    except Exception as e:
        logger.error({"msg": "Live trading failed", "error": str(e)})
        return 1


def run_backtest(
    config_path: str,
    start_date: str,
    end_date: str,
    symbols: list[str],
    use_real_data: bool = True,
    regime_model_path: str | None = None,
    edge_model_path: str | None = None,
) -> int:
    """Run backtesting mode."""
    logger.info({
        "msg": "Starting backtest",
        "config": config_path,
        "start": start_date,
        "end": end_date,
        "symbols": symbols,
        "use_real_data": use_real_data,
    })

    try:
        config = load_config(config_path)

        from pipeline.research.backtest_engine import EventDrivenBacktester, BacktestConfig
        import pandas as pd

        if use_real_data:
            # Load real market data from S3
            logger.info({"msg": "Loading real market data from S3"})

            from infra.data.s3_loader import S3MarketDataLoader, normalize_columns

            loader = S3MarketDataLoader()

            # Load data for first symbol (for now)
            symbol = symbols[0]
            df = loader.load(symbol, start_date, end_date)

            if df.empty:
                logger.error({"msg": "No data loaded from S3", "symbol": symbol})
                return 1

            # Normalize column names
            df = normalize_columns(df)

            logger.info({
                "msg": "S3 data loaded",
                "symbol": symbol,
                "rows": len(df),
                "date_range": f"{df['datetime'].min()} to {df['datetime'].max()}",
            })

            # =================================================================
            # PRODUCTION PIPELINE: Features → ML Models → Signals → Orders
            # =================================================================
            logger.info({"msg": "Running PRODUCTION pipeline with ML models"})

            from pipeline.orchestrator import ProductionPipeline

            # Load trained models if provided
            regime_model = None
            edge_model = None

            if regime_model_path:
                logger.info({"msg": "Loading trained regime model", "path": regime_model_path})
                from pipeline.models.regime.classifier import RegimeClassifierModel
                regime_model = RegimeClassifierModel(
                    classes=config.get("regimes", ["calm", "impulse", "reversal", "breakout", "squeeze", "chop"])
                )
                regime_model.load(regime_model_path)

            if edge_model_path:
                logger.info({"msg": "Loading trained edge model", "path": edge_model_path})
                from pipeline.models.edge.forecaster import EdgeForecasterModel
                edge_model = EdgeForecasterModel()
                edge_model.load(edge_model_path)

            # Initialize pipeline with Sharpe optimization
            pipeline = ProductionPipeline(
                config=config,
                regime_model=regime_model,  # Use trained or fallback
                edge_model=edge_model,      # Use trained or fallback
                use_quality_gate=False,     # TODO: Enable with proper config
                optimize_for_sharpe=True,   # Use optimized thresholds
            )

            # Run complete pipeline
            run_id = f"production_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}"
            signals_df, orders_df = pipeline.run(
                df=df,
                symbol=symbol,
                run_id=run_id,
                current_positions=None,
            )

            if orders_df.empty:
                logger.warning({"msg": "No orders generated by pipeline", "symbol": symbol})
                return 1

            # Convert pipeline orders to backtest format
            # Pipeline gives us: symbol, side, qty, notional_usd, event_time, confidence
            # Backtest needs: symbol, side, qty, event_time, entry_px, exit_px, order_id

            logger.info({"msg": "Converting pipeline orders to backtest format"})

            # Create price lookup
            price_lookup = df.set_index('datetime')['close'].to_dict()

            backtest_orders = []
            for idx, order_row in orders_df.iterrows():
                event_time = order_row['event_time']

                # Find entry price at event time
                if event_time in price_lookup:
                    entry_px = float(price_lookup[event_time])
                else:
                    # Find closest timestamp
                    closest_time = min(price_lookup.keys(), key=lambda t: abs((t - event_time).total_seconds()))
                    entry_px = float(price_lookup[closest_time])

                # Estimate exit price (forward 4 hours or end of data)
                exit_time = event_time + pd.Timedelta(hours=4)
                if exit_time in price_lookup:
                    exit_px = float(price_lookup[exit_time])
                else:
                    # Find closest future time or use last price
                    future_times = [t for t in price_lookup.keys() if t > event_time]
                    if future_times:
                        exit_time = min(future_times, key=lambda t: abs((t - exit_time).total_seconds()))
                        exit_px = float(price_lookup[exit_time])
                    else:
                        # Use entry price + small random move
                        exit_px = entry_px * (1 + np.random.normal(0, 0.005))

                backtest_orders.append({
                    "symbol": symbol,
                    "side": order_row['side'],
                    "qty": 1.0,
                    "event_time": event_time,
                    "entry_px": entry_px,
                    "exit_px": exit_px,
                    "order_id": str(uuid.uuid4()),
                    "confidence": order_row.get('confidence', 0.5),
                    "notional_usd": order_row.get('notional_usd', 10000),
                })

            orders = pd.DataFrame(backtest_orders)

            logger.info({
                "msg": "Pipeline orders converted to backtest format",
                "orders": len(orders),
                "avg_confidence": orders['confidence'].mean() if not orders.empty else 0,
                "total_notional": orders['notional_usd'].sum() if not orders.empty else 0,
            })

            # Get pipeline performance stats
            perf_stats = pipeline.get_performance_stats()
            logger.info({"msg": "Pipeline performance", **perf_stats})

        else:
            # Mock data mode (original behavior)
            logger.info({"msg": "Using mock data (set use_real_data=True for S3 data)"})

            n_orders = 10 * len(symbols)
            np.random.seed(42)
            base_prices = {"BTCUSDT": 50000, "ETHUSDT": 3000, "SOLUSDT": 100}

            mock_prices = []
            mock_exit_prices = []
            for i in range(n_orders):
                symbol = symbols[i % len(symbols)]
                base = base_prices.get(symbol, 50000)
                entry_px = base * (1 + np.random.normal(0, 0.02))
                is_win = np.random.random() < 0.52
                if is_win:
                    exit_px = entry_px * (1 + np.random.uniform(0.005, 0.025))
                else:
                    exit_px = entry_px * (1 - np.random.uniform(0.005, 0.02))
                mock_prices.append(entry_px)
                mock_exit_prices.append(exit_px)

            orders = pd.DataFrame({
                "symbol": symbols * 10,
                "side": ["buy", "sell"] * (5 * len(symbols)),
                "qty": [1.0] * n_orders,
                "event_time": pd.date_range(start_date, periods=n_orders, freq="1h"),
                "entry_px": mock_prices,
                "exit_px": mock_exit_prices,
                "order_id": [str(uuid.uuid4()) for _ in range(n_orders)],
            })

        backtester = EventDrivenBacktester(config=BacktestConfig(
            artifacts_dir=config.get("research", {}).get("artifacts_dir", "artifacts/backtests")
        ))

        run_id = f"backtest_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}"
        results = backtester.run(orders, run_id=run_id)

        logger.info({"msg": "Backtest complete", "results": str(results)})
        return 0

    except Exception as e:
        logger.error({"msg": "Backtest failed", "error": str(e)})
        import traceback
        traceback.print_exc()
        return 1


def run_train(config_path: str, model_type: str) -> int:
    """Train ML models."""
    logger.info({"msg": "Starting model training", "config": config_path, "model": model_type})

    try:
        config = load_config(config_path)

        # TODO: Implement training pipeline
        logger.warning({"msg": "Model training not yet implemented"})
        return 1

    except Exception as e:
        logger.error({"msg": "Training failed", "error": str(e)})
        return 1


def run_validate(config_path: str) -> int:
    """Validate configuration and setup."""
    logger.info({"msg": "Validating configuration", "config": config_path})

    try:
        config = load_config(config_path)
        logger.info({"msg": "Config valid", "app": config.get("app", "unknown")})

        # Check required directories
        artifacts_dir = Path("artifacts")
        if not artifacts_dir.exists():
            logger.warning({"msg": "Creating artifacts directory"})
            artifacts_dir.mkdir(parents=True, exist_ok=True)

        # Check MongoDB connection
        mongo_uri = config.get("data_layer", {}).get("mongo_buffer", {}).get("uri")
        if mongo_uri:
            logger.info({"msg": "MongoDB URI configured", "uri": mongo_uri.split("@")[-1]})
        else:
            logger.warning({"msg": "MongoDB URI not configured"})

        logger.info({"msg": "Validation complete"})
        return 0

    except Exception as e:
        logger.error({"msg": "Validation failed", "error": str(e)})
        return 1


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Trading System",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "mode",
        choices=["live", "backtest", "train", "validate"],
        help="Execution mode",
    )

    parser.add_argument(
        "--config",
        "-c",
        default="configs/base.yaml",
        help="Path to config file (default: configs/base.yaml)",
    )

    parser.add_argument(
        "--symbols",
        "-s",
        nargs="+",
        default=["BTCUSDT"],
        help="Symbols to trade (default: BTCUSDT)",
    )

    parser.add_argument(
        "--start-date",
        default="2024-01-01",
        help="Backtest start date (YYYY-MM-DD)",
    )

    parser.add_argument(
        "--end-date",
        default="2024-12-31",
        help="Backtest end date (YYYY-MM-DD)",
    )

    parser.add_argument(
        "--model-type",
        default="edge",
        choices=["edge", "regime", "all"],
        help="Model type to train",
    )

    parser.add_argument(
        "--regime-model",
        default=None,
        help="Path to trained regime classifier model (.pkl)",
    )

    parser.add_argument(
        "--edge-model",
        default=None,
        help="Path to trained edge forecaster model (.pt)",
    )

    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    # Setup logging
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    logger.info({
        "msg": "Trading system starting",
        "mode": args.mode,
        "config": args.config,
    })

    # Route to appropriate handler
    if args.mode == "live":
        return run_live(args.config, args.symbols)
    elif args.mode == "backtest":
        return run_backtest(
            args.config,
            args.start_date,
            args.end_date,
            args.symbols,
            use_real_data=True,
            regime_model_path=args.regime_model,
            edge_model_path=args.edge_model,
        )
    elif args.mode == "train":
        return run_train(args.config, args.model_type)
    elif args.mode == "validate":
        return run_validate(args.config)
    else:
        logger.error({"msg": "Unknown mode", "mode": args.mode})
        return 1


if __name__ == "__main__":
    sys.exit(main())
