#!/usr/bin/env python3
"""FOUNDATION_AUDIT — reproducible exact-duplicate file scan.

Hashes every git-tracked file (content, not path/name) and reports groups of
2+ files sharing identical content. This is the number
docs/FOUNDATION_AUDIT.md cites for "duplicated files" — regenerate it with
the command below rather than trusting a stale figure.

Usage:
    python3 scripts/dedupe_scan.py            # print summary + top groups
    python3 scripts/dedupe_scan.py --write    # also write docs/DEDUPE.generated.md
"""
from __future__ import annotations

import hashlib
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                         text=True, check=True).stdout
    return [line for line in out.splitlines() if line]


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build_report() -> str:
    by_hash: dict[str, list[str]] = defaultdict(list)
    unreadable: list[str] = []
    for rel in tracked_files():
        p = ROOT / rel
        try:
            by_hash[sha256_of(p)].append(rel)
        except OSError:
            unreadable.append(rel)

    groups = {h: files for h, files in by_hash.items() if len(files) > 1}
    n_duplicated_files = sum(len(files) for files in groups.values())
    n_groups = len(groups)

    lines = [
        "<!-- AUTO-GENERATED by scripts/dedupe_scan.py — do not hand-edit. -->",
        "# Exact-duplicate file scan (content hash, git-tracked files only)",
        "",
        f"- tracked files scanned: {len(tracked_files())}",
        f"- unreadable (skipped): {len(unreadable)}",
        f"- duplicate groups (2+ identical files): {n_groups}",
        f"- files that are part of a duplicate group: {n_duplicated_files}",
        "",
        "Regenerate with: `python3 scripts/dedupe_scan.py --write`",
        "",
        "## Largest duplicate groups (by member count)",
        "",
    ]
    ranked = sorted(groups.items(), key=lambda kv: -len(kv[1]))
    for h, files in ranked[:40]:
        lines.append(f"### {h[:12]}... ({len(files)} files)")
        for f in sorted(files):
            lines.append(f"- {f}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    report = build_report()
    print(report)
    if "--write" in sys.argv:
        out = ROOT / "docs" / "DEDUPE.generated.md"
        out.write_text(report + "\n")
        print(f"\nwrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
